### PR TITLE
Thoughts and comments (feel free to ignore)

### PR DESCRIPTION
**Pull request by jeeftor**
Dont take this code because I wrote it sitting in McDonalds :) 

I think we need the following mods possibly:

1) Elevation can come out of the api endpoints 

image

2) I think we need a get station which you pass an ID to and a get_stations() call ...

If I have actual time I might clean this up but at least you can see what I was thinking.

Lastly I asked ChatGPT to make me data classes for the `/stations` endpoint and this is what it came up with:

```python
import json
from dataclasses import dataclass, field
from typing import List

# Define data classes
@dataclass
class DeviceMeta:
    agl: float
    name: str
    environment: str
    wifi_network_name: str

@dataclass
class Device:
    device_id: int
    serial_number: str
    device_meta: DeviceMeta
    device_type: str
    hardware_revision: str
    firmware_revision: str
    notes: str

@dataclass
class StationMeta:
    elevation: float
    share_with_wf: bool
    share_with_wu: bool

@dataclass
class StationItem:
    location_item_id: int
    station_id: int
    device_id: int
    item: str

@dataclass
class Location:
    station_id: int
    name: str
    public_name: str
    latitude: float
    longitude: float
    station_meta: StationMeta
    devices: List[Device]
    station_items: List[StationItem]

@dataclass
class Status:
    status_code: int
    status_message: str

@dataclass
class JsonResponse:
    status: Status
    locations: List[Location]

# Function to parse JSON data into data classes
def parse_json(json_data):
    def _from_dict(data_class, data):
        fields = {f.name: data.get(f.name) for f in dataclass.fields(data_class)}
        return data_class(**fields)
    
    return _from_dict(JsonResponse, json_data)

# Example JSON data (as a string)
json_str = '''{
  "status": {
    "status_code": 0,
    "status_message": "SUCCESS"
  },
  "locations": [
    {
      "station_id": 67,
      ...
    }
  ]
}'''

# Load and parse JSON data
data = json.loads(json_str)
parsed_data = parse_json(data)

# Now you can access the data through the data class instances
print(parsed_data.status.status_message)  # Example usage
```

### CODE REVIEW

**Comment by jeeftor** [comment]
@briis - I don't want to completely refactor your backing library ... but for HA I think we want to make sure it can handle all of the API Endpoints correctly. I also think there _may_ be a way to more efficiently just READ json data into a `@dataclass` ... 

```
    data = json.loads(json_str)
    return data_class(**data)
```

Anyways ... I will probably mess around a bit on this PR which you can feel free to ignore... its better than doing what I'm **supposed to do**

**Comment by briis** [comment]
Hi Jeff,
Exiting stuff 👍 I will look forward to take a deeper look when we hit the holidays, as Thursday and Friday are swamped with 'real' work.

**Comment by briis** [comment]
Hi Jeff,
It's Christmas and i will not spend a lot of time today on this. First glance, I like what you are trying to do by simplifying things. One thing that pops up is: In most of the current dataclasses there are a lot of calculated values, and I don't see these in your suggestion. How do you expect to handle those?

**Comment by jeeftor** [comment]
@briis  - are you on the HA discord? we should connect there - easier to talk. I'm back from vacation and although I have to work this week it will be a light week and be happy to toss some ideas back and forth. I can also bring in one of the mods so we can the 3 of us discuss the best way to do HA / Core integration.

**Comment by briis** [comment]
Hi @jeeftor 
Yes I have access to the HA Discord. My user is b_riis. But it is not a place I am very often, as I find it too overwhelming and to hard to find anything in Discord. Most likely because I don't use it often (or maybe the UI sucks)
Anyway I guess we are also in two different timezones, as I live in Denmark (GMT+1) and I guess you live in the US?

Feel free to reach out in Discord, and I will do my best to reply.

**Comment by jeeftor** [comment]
I'm in the US. I catch @joostlek (Netherlands) often on discord. I also find the general chat overwhelming - but - DM functionality is good. I'm happy to punt on this branch.

**Comment by joostlek** [comment]
Please keep in mind that I have no life so enough time to respond

**Comment by jeeftor** [comment]
@briis  -> I found the raw OpenAPI Spec btw

https://weatherflow.github.io/Tempest/api/swagger/swagger.json


image

**Comment by jeeftor** [comment]
https://github.com/jeeftor/Weatherflow-OpenApi-Python

I tossed the generate client code up for kicks.

**Pull request closed without merging**
